### ISSUE TITLE
CUP file parsing - comma in Title and Description fields

### ISSUE THREAD

**Issue by owesweden** [ekurutepe/Iguazu#10]
Getting components  separated by "," does not work...

Comma in title field:
"Björbo Bro, Väst","BJRBBR",SE,6027.333N,01443.917E,,1,,,,"Turn Point"

Comma in description field:
"Ekeby Flp","EKEBY",SE,5922.833N,01626.383E,12m,2,900,830ft,123.200,"Home Field, Finish Point, Turn Point, ESSC"

**Comment by ekurutepe** [comment]
This was previously fixed. Added a test to make sure it stays that way.
