### ISSUE TITLE
Allow invalid fixes in an IGC file

### ISSUE THREAD

**Issue by ekurutepe** [ekurutepe/Iguazu#11]
Currently Iguazu assumes all fix lines in an IGC file are valid and expects all lines to parse correctly but this is clearly not always the case. (see the example in #5)

The quick solution is to allow nil fixes in the fixes array to indicate missing/failed fixes.

**Comment by owesweden** [comment]
I believe that IGC/FAI has a time limit for missing fixes. That should be a part of the file validity check.

**Comment by ekurutepe** [comment]
@owesweden yes that's a good point and would be the best solution. 

I am going to follow a two step process because of my own time constraints:
- in the first fix in a few days, this won't crash anymore and I'll let the validity check be the consumer application's problem. The consumer can check the fixes array and see if there are any nil fixes and compute max missing time duration. 
- in a later update the validity check can be moved into Iguazu.

If you feel like the validity check is something you'd like to work on, I'm happy to accept your contribution into Iguazu.

**Comment by owesweden** [comment]
Gearing up into my new career...

**Comment by ekurutepe** [comment]
You're grounded anyway, right? 👨‍✈️

**Comment by owesweden** [comment]
Yes...

**Comment by ekurutepe** [comment]
fixed by https://github.com/ekurutepe/Iguazu/commit/49ae0d2cfe7d21c705a7ee3d0e542e1d70dc7bdd
